# Generated by Django 4.0.5 on 2022-10-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_ipadress_article_hits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipadress',
            options={'verbose_name': 'آدرس آیپی', 'verbose_name_plural': 'آدرس آیپی'},
        ),
    ]
