# Generated by Django 4.0.5 on 2022-09-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_is_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Is_author',
            field=models.BooleanField(default=False, verbose_name='وضعیت نویسندگی'),
        ),
    ]
