# Generated by Django 4.0.5 on 2022-10-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile_Avatar',
            field=models.ImageField(default='default_avatar.png', upload_to='Profile', verbose_name='عکس پروفایل'),
        ),
    ]
